# Generated by Django 3.2.9 on 2021-11-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='update',
            new_name='updated',
        ),
    ]
