# Generated by Django 3.2.9 on 2021-11-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_as_flaot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
