# Generated by Django 3.2.9 on 2021-12-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_quantity_as_flaot'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('test', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
