# Generated by Django 3.2.9 on 2022-01-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shopitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
