# Generated by Django 3.2.9 on 2022-01-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_shopitems_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitems',
            name='temp',
        ),
    ]
